/*
 * Copyright 2017 StreamSets Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.streamsets.datacollector.runner;

import com.google.common.base.Preconditions;
import com.streamsets.datacollector.runner.production.ReportErrorDelegate;
import com.streamsets.pipeline.api.Record;
import com.streamsets.pipeline.api.StageException;
import com.streamsets.pipeline.api.impl.ErrorMessage;
import com.streamsets.pipeline.api.impl.Utils;
import com.streamsets.pipeline.api.interceptor.Interceptor;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Error sink is an entity that ends up collecting error records as they are generated by the stages.
 */
public class ErrorSink implements ReportErrorDelegate {

  private final Map<String, List<ErrorMessage>> stageErrors;
  private final Map<String, List<Record>> errorRecords;
  private final Map<String, List<? extends Interceptor>> interceptors;
  private int size;
  private int totalErrorRecords;
  private int totalErrorMessages;

  public ErrorSink() {
    stageErrors = new LinkedHashMap<>();
    errorRecords = new LinkedHashMap<>();
    interceptors = new HashMap<>();
    size = 0;
    totalErrorMessages = 0;
    totalErrorRecords = 0;
  }

  // for SDK
  public void clear() {
    stageErrors.clear();
    errorRecords.clear();
  }

  @Override
  public void reportError(String stage, ErrorMessage errorMessage) {
    addError(stageErrors, stage, errorMessage);
    totalErrorMessages++;
  }

  public void registerInterceptorsForStage(String stage, List<? extends Interceptor> interceptors) {
    Preconditions.checkState(!this.interceptors.containsKey(stage), Utils.format("Interceptors for stage '{}' already registered", stage));
    this.interceptors.put(stage, interceptors);
  }

  public void addRecord(String stage, Record errorRecord) {
    addError(errorRecords, stage, errorRecord);
    totalErrorRecords++;
  }

  public Map<String, List<ErrorMessage>> getStageErrors() {
    return stageErrors;
  }

  // TODO: THis needs to be dropped as it's unprotected
  public Map<String, List<Record>> getErrorRecords() {
    return errorRecords;
  }

  private <T> void addError(Map<String, List<T>> map, String stage, T error) {
    List<T> errors = map.computeIfAbsent(stage, k -> new ArrayList<>());
    errors.add(error);
    size++;
  }

  @SuppressWarnings("unchecked")
  private <T> List<T> getErrors(Map<String, List<T>> map, String stage) {
    List<T> errors = map.get(stage);
    return (errors != null) ? errors : Collections.emptyList();
  }

  public List<Record> getErrorRecords(String stage) throws StageException {
    Preconditions.checkState(interceptors.containsKey(stage), Utils.format("No interceptors registered for stage '{}'", stage));
    List<Record> records = getErrors(errorRecords, stage);
    if(records.isEmpty()) {
      return records;
    }

    return intercept(records, interceptors.get(stage));
  }

  public List<ErrorMessage> getStageErrors(String stage) {
    return getErrors(stageErrors, stage);
  }

  public int size() {
    return size;
  }

  @Override
  public String toString() {
    Set<String> stages = new HashSet<>(errorRecords.keySet());
    stages.addAll(stageErrors.keySet());
    return Utils.format("ErrorSink[reportingInstances='{}' size='{}']", stages, size());
  }

  public int getTotalErrorRecords() {
    return totalErrorRecords;
  }

  public int getTotalErrorMessages() {
    return totalErrorMessages;
  }

  private List<Record> intercept(List<Record> records, List<? extends Interceptor> interceptors) throws StageException {
    for(Interceptor interceptor : interceptors)  {
      records = interceptor.intercept(records);
    }

    return records;
  }
}
