/*
 * Copyright 2017 StreamSets Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Extensions.proto

package com.streamsets.pipeline.lib.util;

public final class ExtensionsProto {
  private ExtensionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.stringField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.doubleField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.floatField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.boolField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.intField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.longField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.bytesField);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.residenceAddress);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.factoryAddress);
    registry.add(com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.officeAddress);
  }
  public interface PersonExtensionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code util.PersonExtension}
   */
  public static final class PersonExtension extends
      com.google.protobuf.GeneratedMessage
      implements PersonExtensionOrBuilder {
    // Use PersonExtension.newBuilder() to construct.
    private PersonExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonExtension(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonExtension defaultInstance;
    public static PersonExtension getDefaultInstance() {
      return defaultInstance;
    }

    public PersonExtension getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonExtension> PARSER =
        new com.google.protobuf.AbstractParser<PersonExtension>() {
      public PersonExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonExtension(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonExtension> getParserForType() {
      return PARSER;
    }

    public interface NestedPersonExtensionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code util.PersonExtension.NestedPersonExtension}
     */
    public static final class NestedPersonExtension extends
        com.google.protobuf.GeneratedMessage
        implements NestedPersonExtensionOrBuilder {
      // Use NestedPersonExtension.newBuilder() to construct.
      private NestedPersonExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private NestedPersonExtension(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final NestedPersonExtension defaultInstance;
      public static NestedPersonExtension getDefaultInstance() {
        return defaultInstance;
      }

      public NestedPersonExtension getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private NestedPersonExtension(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_NestedPersonExtension_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_NestedPersonExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.Builder.class);
      }

      public static com.google.protobuf.Parser<NestedPersonExtension> PARSER =
          new com.google.protobuf.AbstractParser<NestedPersonExtension>() {
        public NestedPersonExtension parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NestedPersonExtension(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<NestedPersonExtension> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code util.PersonExtension.NestedPersonExtension}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtensionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_NestedPersonExtension_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_NestedPersonExtension_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.Builder.class);
        }

        // Construct using com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_NestedPersonExtension_descriptor;
        }

        public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension getDefaultInstanceForType() {
          return com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.getDefaultInstance();
        }

        public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension build() {
          com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension buildPartial() {
          com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension result = new com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension) {
            return mergeFrom((com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension other) {
          if (other == com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:util.PersonExtension.NestedPersonExtension)
      }

      static {
        defaultInstance = new NestedPersonExtension(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:util.PersonExtension.NestedPersonExtension)
      public static final int RESIDENCEADDRESS_FIELD_NUMBER = 101;
      /**
       * <code>extend .util.Person { ... }</code>
       */
      public static final
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.streamsets.pipeline.lib.util.PersonProto.Person,
          java.lang.String> residenceAddress = com.google.protobuf.GeneratedMessage
              .newMessageScopedGeneratedExtension(
            com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.NestedPersonExtension.getDefaultInstance(),
            0,
            java.lang.String.class,
            null);
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code util.PersonExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.Builder.class);
      }

      // Construct using com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_PersonExtension_descriptor;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension getDefaultInstanceForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.getDefaultInstance();
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension build() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension buildPartial() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension result = new com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension) {
          return mergeFrom((com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension other) {
        if (other == com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.streamsets.pipeline.lib.util.ExtensionsProto.PersonExtension) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:util.PersonExtension)
    }

    static {
      defaultInstance = new PersonExtension(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:util.PersonExtension)
  }

  public interface EngineerExtensionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code util.EngineerExtension}
   */
  public static final class EngineerExtension extends
      com.google.protobuf.GeneratedMessage
      implements EngineerExtensionOrBuilder {
    // Use EngineerExtension.newBuilder() to construct.
    private EngineerExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EngineerExtension(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EngineerExtension defaultInstance;
    public static EngineerExtension getDefaultInstance() {
      return defaultInstance;
    }

    public EngineerExtension getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EngineerExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_EngineerExtension_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_EngineerExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.Builder.class);
    }

    public static com.google.protobuf.Parser<EngineerExtension> PARSER =
        new com.google.protobuf.AbstractParser<EngineerExtension>() {
      public EngineerExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EngineerExtension(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EngineerExtension> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code util.EngineerExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_EngineerExtension_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_EngineerExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.Builder.class);
      }

      // Construct using com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_EngineerExtension_descriptor;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension getDefaultInstanceForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.getDefaultInstance();
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension build() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension buildPartial() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension result = new com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension) {
          return mergeFrom((com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension other) {
        if (other == com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:util.EngineerExtension)
    }

    static {
      defaultInstance = new EngineerExtension(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:util.EngineerExtension)
    public static final int FACTORYADDRESS_FIELD_NUMBER = 201;
    /**
     * <code>extend .util.Engineer { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.streamsets.pipeline.lib.util.EngineerProto.Engineer,
        java.lang.String> factoryAddress = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.streamsets.pipeline.lib.util.ExtensionsProto.EngineerExtension.getDefaultInstance(),
          0,
          java.lang.String.class,
          null);
  }

  public interface ExecutiveExtensionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code util.ExecutiveExtension}
   */
  public static final class ExecutiveExtension extends
      com.google.protobuf.GeneratedMessage
      implements ExecutiveExtensionOrBuilder {
    // Use ExecutiveExtension.newBuilder() to construct.
    private ExecutiveExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExecutiveExtension(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExecutiveExtension defaultInstance;
    public static ExecutiveExtension getDefaultInstance() {
      return defaultInstance;
    }

    public ExecutiveExtension getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExecutiveExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_ExecutiveExtension_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_ExecutiveExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.Builder.class);
    }

    public static com.google.protobuf.Parser<ExecutiveExtension> PARSER =
        new com.google.protobuf.AbstractParser<ExecutiveExtension>() {
      public ExecutiveExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecutiveExtension(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExecutiveExtension> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code util.ExecutiveExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_ExecutiveExtension_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_ExecutiveExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.class, com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.Builder.class);
      }

      // Construct using com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.internal_static_util_ExecutiveExtension_descriptor;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension getDefaultInstanceForType() {
        return com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.getDefaultInstance();
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension build() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension buildPartial() {
        com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension result = new com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension) {
          return mergeFrom((com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension other) {
        if (other == com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:util.ExecutiveExtension)
    }

    static {
      defaultInstance = new ExecutiveExtension(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:util.ExecutiveExtension)
    public static final int OFFICEADDRESS_FIELD_NUMBER = 301;
    /**
     * <code>extend .util.Executive { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.streamsets.pipeline.lib.util.ExecutiveProto.Executive,
        java.lang.String> officeAddress = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.streamsets.pipeline.lib.util.ExtensionsProto.ExecutiveExtension.getDefaultInstance(),
          0,
          java.lang.String.class,
          null);
  }

  public static final int STRINGFIELD_FIELD_NUMBER = 401;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.String> stringField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DOUBLEFIELD_FIELD_NUMBER = 402;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.Double> doubleField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Double.class,
        null);
  public static final int FLOATFIELD_FIELD_NUMBER = 403;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.Float> floatField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int BOOLFIELD_FIELD_NUMBER = 404;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.Boolean> boolField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int INTFIELD_FIELD_NUMBER = 405;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.Integer> intField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int LONGFIELD_FIELD_NUMBER = 406;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      java.lang.Long> longField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int BYTESFIELD_FIELD_NUMBER = 407;
  /**
   * <code>extend .util.Employee { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.streamsets.pipeline.lib.util.EmployeeProto.Employee,
      com.google.protobuf.ByteString> bytesField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.protobuf.ByteString.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_util_PersonExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_util_PersonExtension_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_util_PersonExtension_NestedPersonExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_util_PersonExtension_NestedPersonExtension_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_util_EngineerExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_util_EngineerExtension_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_util_ExecutiveExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_util_ExecutiveExtension_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Extensions.proto\022\004util\032\014Person.proto\032\016" +
      "Engineer.proto\032\017Executive.proto\032\016Employe" +
      "e.proto\"R\n\017PersonExtension\032?\n\025NestedPers" +
      "onExtension2&\n\020residenceAddress\022\014.util.P" +
      "erson\030e \001(\t\"<\n\021EngineerExtension2\'\n\016fact" +
      "oryAddress\022\016.util.Engineer\030\311\001 \001(\t\"=\n\022Exe" +
      "cutiveExtension2\'\n\rofficeAddress\022\017.util." +
      "Executive\030\255\002 \001(\t:(\n\013stringField\022\016.util.E" +
      "mployee\030\221\003 \001(\t:\002NY:.\n\013doubleField\022\016.util" +
      ".Employee\030\222\003 \001(\001:\0103534.234:+\n\nfloatField",
      "\022\016.util.Employee\030\223\003 \001(\002:\006343.34:(\n\tboolF" +
      "ield\022\016.util.Employee\030\224\003 \001(\010:\004true:(\n\010int" +
      "Field\022\016.util.Employee\030\225\003 \001(\005:\00543243:.\n\tl" +
      "ongField\022\016.util.Employee\030\226\003 \001(\003:\n2343254" +
      "354:,\n\nbytesField\022\016.util.Employee\030\227\003 \001(\014" +
      ":\007NewYorkB3\n com.streamsets.pipeline.lib" +
      ".utilB\017ExtensionsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_util_PersonExtension_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_util_PersonExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_util_PersonExtension_descriptor,
              new java.lang.String[] { });
          internal_static_util_PersonExtension_NestedPersonExtension_descriptor =
            internal_static_util_PersonExtension_descriptor.getNestedTypes().get(0);
          internal_static_util_PersonExtension_NestedPersonExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_util_PersonExtension_NestedPersonExtension_descriptor,
              new java.lang.String[] { });
          internal_static_util_EngineerExtension_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_util_EngineerExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_util_EngineerExtension_descriptor,
              new java.lang.String[] { });
          internal_static_util_ExecutiveExtension_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_util_ExecutiveExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_util_ExecutiveExtension_descriptor,
              new java.lang.String[] { });
          stringField.internalInit(descriptor.getExtensions().get(0));
          doubleField.internalInit(descriptor.getExtensions().get(1));
          floatField.internalInit(descriptor.getExtensions().get(2));
          boolField.internalInit(descriptor.getExtensions().get(3));
          intField.internalInit(descriptor.getExtensions().get(4));
          longField.internalInit(descriptor.getExtensions().get(5));
          bytesField.internalInit(descriptor.getExtensions().get(6));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.streamsets.pipeline.lib.util.PersonProto.getDescriptor(),
          com.streamsets.pipeline.lib.util.EngineerProto.getDescriptor(),
          com.streamsets.pipeline.lib.util.ExecutiveProto.getDescriptor(),
          com.streamsets.pipeline.lib.util.EmployeeProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
