/*
 * Copyright 2017 StreamSets Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.streamsets.pipeline.stage.destination.solr;

import com.streamsets.pipeline.api.Config;
import com.streamsets.pipeline.api.StageException;
import com.streamsets.pipeline.api.StageUpgrader;
import com.streamsets.pipeline.api.impl.Utils;

import java.util.ArrayList;
import java.util.List;

public class SolrDTargetUpgrader implements StageUpgrader {

  @Override
  public List<Config> upgrade(
      String library,
      String stageName,
      String stageInstance,
      int fromVersion,
      int toVersion,
      List<Config> configs
  ) throws StageException {
    switch (fromVersion) {
      case 1:
        upgradeV1ToV2(configs);
        if (toVersion == 2) {
          break;
        }
        // fall through
      case 2:
        upgradeV2ToV3(configs);
        if (toVersion == 3) {
          break;
        }
        // fall through
      case 3:
        upgradeV3ToV4(configs);
        if (toVersion == 4) {
          break;
        }
        // fall through
      case 4:
        upgradeV4ToV5(configs);
        break;
      default:
        throw new IllegalStateException(Utils.format("Unexpected fromVersion {}", fromVersion));
    }
    return configs;
  }

  private static void upgradeV1ToV2(List<Config> configs) {
    boolean configExists = false;
    for (Config config : configs) {
      if (config.getName().equals("defaultCollection")) {
        configExists = true;
        break;
      }
    }

    if (!configExists) {
      configs.add(new Config("defaultCollection", ""));
    }

  }

  private static void upgradeV2ToV3(List<Config> configs) {
    configs.add(new Config("waitFlush", true));
    configs.add(new Config("waitSearcher", true));
    configs.add(new Config("softCommit", false));
    configs.add(new Config("ignoreOptionalFields", true));
  }

  private static void upgradeV3ToV4(List<Config> configs) {
    configs.add(new Config("fieldsAlreadyMappedInRecord", false));
    configs.add(new Config("recordSolrFieldsPath", "/"));
  }

  private static void upgradeV4ToV5(List<Config> configs) {
    configs.add(new Config("autogeneratedFields", new ArrayList<String>()));
  }
}
