/*
 * Copyright 2017 StreamSets Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Executive.proto

package com.streamsets.pipeline.lib.util;

public final class ExecutiveProto {
  private ExecutiveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExecutiveOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Executive> {

    // required .util.Person person = 1;
    /**
     * <code>required .util.Person person = 1;</code>
     */
    boolean hasPerson();
    /**
     * <code>required .util.Person person = 1;</code>
     */
    com.streamsets.pipeline.lib.util.PersonProto.Person getPerson();
    /**
     * <code>required .util.Person person = 1;</code>
     */
    com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder getPersonOrBuilder();

    // required string employeeId = 2;
    /**
     * <code>required string employeeId = 2;</code>
     */
    boolean hasEmployeeId();
    /**
     * <code>required string employeeId = 2;</code>
     */
    java.lang.String getEmployeeId();
    /**
     * <code>required string employeeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmployeeIdBytes();
  }
  /**
   * Protobuf type {@code util.Executive}
   */
  public static final class Executive extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Executive> implements ExecutiveOrBuilder {
    // Use Executive.newBuilder() to construct.
    private Executive(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.streamsets.pipeline.lib.util.ExecutiveProto.Executive, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Executive(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Executive defaultInstance;
    public static Executive getDefaultInstance() {
      return defaultInstance;
    }

    public Executive getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Executive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.streamsets.pipeline.lib.util.PersonProto.Person.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(com.streamsets.pipeline.lib.util.PersonProto.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              employeeId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.streamsets.pipeline.lib.util.ExecutiveProto.internal_static_util_Executive_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.streamsets.pipeline.lib.util.ExecutiveProto.internal_static_util_Executive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.class, com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.Builder.class);
    }

    public static com.google.protobuf.Parser<Executive> PARSER =
        new com.google.protobuf.AbstractParser<Executive>() {
      public Executive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Executive(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Executive> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .util.Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private com.streamsets.pipeline.lib.util.PersonProto.Person person_;
    /**
     * <code>required .util.Person person = 1;</code>
     */
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .util.Person person = 1;</code>
     */
    public com.streamsets.pipeline.lib.util.PersonProto.Person getPerson() {
      return person_;
    }
    /**
     * <code>required .util.Person person = 1;</code>
     */
    public com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder getPersonOrBuilder() {
      return person_;
    }

    // required string employeeId = 2;
    public static final int EMPLOYEEID_FIELD_NUMBER = 2;
    private java.lang.Object employeeId_;
    /**
     * <code>required string employeeId = 2;</code>
     */
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string employeeId = 2;</code>
     */
    public java.lang.String getEmployeeId() {
      java.lang.Object ref = employeeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          employeeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string employeeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeIdBytes() {
      java.lang.Object ref = employeeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      person_ = com.streamsets.pipeline.lib.util.PersonProto.Person.getDefaultInstance();
      employeeId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPerson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmployeeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPerson().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.streamsets.pipeline.lib.util.ExecutiveProto.Executive>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, person_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmployeeIdBytes());
      }
      extensionWriter.writeUntil(400, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmployeeIdBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.streamsets.pipeline.lib.util.ExecutiveProto.Executive prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code util.Executive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.streamsets.pipeline.lib.util.ExecutiveProto.Executive, Builder> implements com.streamsets.pipeline.lib.util.ExecutiveProto.ExecutiveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.streamsets.pipeline.lib.util.ExecutiveProto.internal_static_util_Executive_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.streamsets.pipeline.lib.util.ExecutiveProto.internal_static_util_Executive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.class, com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.Builder.class);
      }

      // Construct using com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = com.streamsets.pipeline.lib.util.PersonProto.Person.getDefaultInstance();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.streamsets.pipeline.lib.util.ExecutiveProto.internal_static_util_Executive_descriptor;
      }

      public com.streamsets.pipeline.lib.util.ExecutiveProto.Executive getDefaultInstanceForType() {
        return com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.getDefaultInstance();
      }

      public com.streamsets.pipeline.lib.util.ExecutiveProto.Executive build() {
        com.streamsets.pipeline.lib.util.ExecutiveProto.Executive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.streamsets.pipeline.lib.util.ExecutiveProto.Executive buildPartial() {
        com.streamsets.pipeline.lib.util.ExecutiveProto.Executive result = new com.streamsets.pipeline.lib.util.ExecutiveProto.Executive(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (personBuilder_ == null) {
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.employeeId_ = employeeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.streamsets.pipeline.lib.util.ExecutiveProto.Executive) {
          return mergeFrom((com.streamsets.pipeline.lib.util.ExecutiveProto.Executive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.streamsets.pipeline.lib.util.ExecutiveProto.Executive other) {
        if (other == com.streamsets.pipeline.lib.util.ExecutiveProto.Executive.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        if (other.hasEmployeeId()) {
          bitField0_ |= 0x00000002;
          employeeId_ = other.employeeId_;
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPerson()) {

          return false;
        }
        if (!hasEmployeeId()) {

          return false;
        }
        if (!getPerson().isInitialized()) {

          return false;
        }
        if (!extensionsAreInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.streamsets.pipeline.lib.util.ExecutiveProto.Executive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.streamsets.pipeline.lib.util.ExecutiveProto.Executive) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .util.Person person = 1;
      private com.streamsets.pipeline.lib.util.PersonProto.Person person_ = com.streamsets.pipeline.lib.util.PersonProto.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.streamsets.pipeline.lib.util.PersonProto.Person, com.streamsets.pipeline.lib.util.PersonProto.Person.Builder, com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder> personBuilder_;
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public com.streamsets.pipeline.lib.util.PersonProto.Person getPerson() {
        if (personBuilder_ == null) {
          return person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public Builder setPerson(com.streamsets.pipeline.lib.util.PersonProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public Builder setPerson(
          com.streamsets.pipeline.lib.util.PersonProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public Builder mergePerson(com.streamsets.pipeline.lib.util.PersonProto.Person value) {
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              person_ != com.streamsets.pipeline.lib.util.PersonProto.Person.getDefaultInstance()) {
            person_ =
              com.streamsets.pipeline.lib.util.PersonProto.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = com.streamsets.pipeline.lib.util.PersonProto.Person.getDefaultInstance();
          onChanged();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public com.streamsets.pipeline.lib.util.PersonProto.Person.Builder getPersonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      public com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_;
        }
      }
      /**
       * <code>required .util.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.streamsets.pipeline.lib.util.PersonProto.Person, com.streamsets.pipeline.lib.util.PersonProto.Person.Builder, com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder>
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.streamsets.pipeline.lib.util.PersonProto.Person, com.streamsets.pipeline.lib.util.PersonProto.Person.Builder, com.streamsets.pipeline.lib.util.PersonProto.PersonOrBuilder>(
                  person_,
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // required string employeeId = 2;
      private java.lang.Object employeeId_ = "";
      /**
       * <code>required string employeeId = 2;</code>
       */
      public boolean hasEmployeeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string employeeId = 2;</code>
       */
      public java.lang.String getEmployeeId() {
        java.lang.Object ref = employeeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          employeeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string employeeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmployeeIdBytes() {
        java.lang.Object ref = employeeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          employeeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string employeeId = 2;</code>
       */
      public Builder setEmployeeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        employeeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeId = 2;</code>
       */
      public Builder clearEmployeeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        employeeId_ = getDefaultInstance().getEmployeeId();
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeId = 2;</code>
       */
      public Builder setEmployeeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        employeeId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:util.Executive)
    }

    static {
      defaultInstance = new Executive(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:util.Executive)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_util_Executive_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_util_Executive_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Executive.proto\022\004util\032\014Person.proto\"E\n" +
      "\tExecutive\022\034\n\006person\030\001 \002(\0132\014.util.Person" +
      "\022\022\n\nemployeeId\030\002 \002(\t*\006\010\254\002\020\220\003B2\n com.stre" +
      "amsets.pipeline.lib.utilB\016ExecutiveProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_util_Executive_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_util_Executive_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_util_Executive_descriptor,
              new java.lang.String[] { "Person", "EmployeeId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.streamsets.pipeline.lib.util.PersonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
